package com.example.demo.models;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Enumerated;
import jakarta.persistence.EnumType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
// import jakarta.validation.constraints.Future;
// import jakarta.validation.constraints.NotBlank;
// import jakarta.validation.constraints.NotNull;
// import jakarta.validation.constraints.Size;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;

@Entity // Marks this class as a JPA entity
@Data // Automatically generates getters, setters, toString, equals and hashCode
@NoArgsConstructor // Empty constructor required by JPA
@AllArgsConstructor // Constructor with all fields
public class Tarea {

    @Id // Primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Auto-generated by DB
    private Long id;

    // @NotBlank(message = "La descripción no puede estar vacía") // Must not be null/blank
    // @Size(min = 5, message = "La descripción debe tener al menos 5 caracteres") // Minimum length
    @Column(name = "descripcion") // Maps field to column
    private String descripcion;

    @Column(name = "completada") // Task completed or not
    private boolean completada;

    @Column(name = "fecha_limite") // Due date
    // @Future(message = "La fecha límite debe ser futura") // Must be in the future
    private LocalDate fechaLimite;

    // @NotNull(message = "La prioridad es obligatoria") // Cannot be null
    @Enumerated(EnumType.STRING) // Stored as string: 'BAJA', 'MEDIA', 'ALTA'
    @Column(name = "prioridad")
    private Prioridad prioridad;

    // Internal enum for priority levels
    public enum Prioridad {
        BAJA, MEDIA, ALTA
    }
}
